export { default as Home } from './Home'
export { default as AppStore } from './AppStore'
export { default as Calendar} from './Calendar'
export { default as Graph} from './Graph'
export { default as HomeAfter } from './HomeAfter'
export { default as Survey} from './Survey'
export { default as Input} from './Input'
export { default as Main} from './Main'
export { default as Kaya} from './Kaya'
export { default as Description } from './Description'
export { default as End} from './End'
export { default as Splash} from './Splash'