export { default as Home } from './Home'
export { default as AppStoreA } from './AppStoreA'
export { default as AppStoreB } from './AppStoreB'
export { default as Calendar} from './Calendar'
export { default as Graph} from './Graph'
export { default as HomeAfter } from './HomeAfter'